role: unit
id:   app-web

reactor:
  provider: tilt
  context: ./

  blueprints:
    - env:  dev
      path: ./infra/dev/tilt/Tiltfile

    - env:  staging
      path: ./infra/staging/tilt/Tiltfile

  standalone:
    blueprints:
      - env: dev
        path: ./infra/dev/tilt/standalone.Tiltfile

      - env: staging
        path: ./infra/staging/tilt/standalone.Tiltfile
