files:
  - source: /messages/uk/*.json
    translation: /messages/%two_letters_code%/%original_file_name%

  - source: /src/shared/assets/content/uk/**/*.mdx
    translation: /src/shared/assets/content/%two_letters_code%/**/%original_file_name%
